version: '3.8'

services:
  psql-db:
    image: postgres-${ENV}
    container_name: psql-db
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin7-${ENV}
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: 'False'
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
    ports:
      - 5050:80
    networks:
      - app-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  frontend:
    image: web-app-${ENV}
    container_name: frontend-${ENV}
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_APP_API_URL: ${VITE_APP_API_URL}
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - app-network
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  backend:
    image: backend-${ENV}
    container_name: backend-${ENV}
    build:
      context: ./BookApi
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      ConnectionStrings__BuuttiBookCS: ${CONNECTION_STRING}
    depends_on:
      - psql-db
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
    name: db-data-volume-${ENV}
  pgadmin-data:
    name: db-pgadmin-volume-${ENV}
